### ISSUE TITLE
builtin_templates.json file description outdated my github account 

### ISSUE THREAD

**Issue by MasterNama17083** [JargeZ/ntscqt#28]
Hello @JargeZ. My GitHub account is outdated, Please make sure to change the @Masternama to @MasterNama17083 mention.
![image](https://user-images.githubusercontent.com/80534869/149652060-6c6c513b-db39-4ebf-a2bb-a7462f725679.png)

Here's commit: [`28b9e5e`](https://github.com/JargeZ/ntscqt/commit/6ecc326c1406c07b83f0d7d92cd49a5867c15da2)

**Comment by JargeZ** [comment]
Thanks!
I'm re-commited preset
