### ISSUE TITLE
Render Issue: Top pixels issue

### ISSUE THREAD

**Issue by BrowserTheGamer5** [JargeZ/ntscqt#38]
When I look at the render preview, it seems like the effect isn't being applied to the topmost pixels.

![issue01](https://user-images.githubusercontent.com/91436972/153680932-6183485d-ca83-4706-adc2-8c8fdf3734d5.png)

This also happens when viewing the output .mp4 in a media player (i used VLC):

https://user-images.githubusercontent.com/91436972/153681106-fed4362a-9e3a-4afb-823e-1f49a9168e2c.mp4

I have tried restarting my computer, to no avail.

I've checked some tests online and they seem to have the same issue.

**Comment by JargeZ** [comment]
Fixed in #45
Appear in next release
