### ISSUE TITLE
'ProcessAudioCheckBox'

### ISSUE THREAD

**Issue by corneliusdevun** [JargeZ/ntscqt#57]
When attempting to render a video I am getting the error in terminal: 

2022-08-24 20:46:59.162 | ERROR    | __main__:crash_handler:20 - Uncaught exception: 'NtscApp' object has no attribute 'ProcessAudioCheckBox'
NoneType: None

If anyone could help that would be dope. I am on a M1 Mac Studio

**Comment by MogManek** [comment]
Same thing happens to me on Windows 10. Weird.

**Comment by corneliusdevun** [comment]
Odd > Same thing happens to me on Windows 10. Weird.

**Comment by corneliusdevun** [comment]
> Same thing happens to me on Windows 10. Weird.

So odd...hoping they get it running soon again or give us a solution. I've been attempting to troubleshoot it at home but nothing yet.

**Comment by corneliusdevun** [comment]
[ntscqt_last_debug_log.log](https://github.com/JargeZ/ntscqt/files/9448784/ntscqt_last_debug_log.log)

This is my log file from the crash(s)

**Comment by jkrosado** [comment]
same here on an intel mac with macos catalina 10.15.7

**Comment by klassixx** [comment]
I get the same error and crash, but I have at least found a workaround for now. In app/NtscApp.py, find the `self.audio_filtering()` line and comment it out (around line 562) so that it reads.

```
        self.setup_renderer()
        self.toggle_main_effect()
        self.lossless_exporting()
        #self.audio_filtering()
        self.progressBar.setValue(1)
        self.videoRenderer.render_data = render_data
        self.thread.start()
```


I'm brand new to the app so I don't know if this app actually does any audio processing, but at least the video renders for me.

**Comment by JargeZ** [comment]
> Sorry, this is a bug that got into the master from the pull request, fixed In main now.
> The main branch isn't green yet, so if you're running from source, check it out yourself.
> Or use the checkout for the release version

_Originally posted by @JargeZ in https://github.com/JargeZ/ntscqt/issues/67#issuecomment-1369056105_
