### ISSUE TITLE
help

### ISSUE THREAD

**Issue by TheGachaGamerStudios** [JargeZ/ntscqt#67]
When I try to render, it closes.

**Comment by DevelopCMD** [comment]
Same here. I am on Arch Linux

**Comment by childprof** [comment]
same (clicking render and accepting the new filename crashes without an output). rendering individual frames works fine though.
[ntscqt_last_debug_log.log](https://github.com/JargeZ/ntscqt/files/10283765/ntscqt_last_debug_log.log)

**Comment by zvpyp** [comment]
in #57 there's a temporal solution. Basically comment the line 562 in NtscApp.py

**Comment by JargeZ** [comment]
Sorry, this is a bug that got into the master from the pull request, fixed In main now.
The main branch isn't green yet, so if you're running from source, check it out yourself.
Or use the checkout for the release version
